name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Download libOQS
        run: |
          sudo mkdir /debs/
          sudo wget --directory-prefix=/debs/ https://github.com/ShubhamKarala/liboqs-debian/releases/download/0.7.2/liboqs-dbgsym_0.7.2_amd64.deb
          sudo wget --directory-prefix=/debs/ https://github.com/ShubhamKarala/liboqs-debian/releases/download/0.7.2/liboqs-dev_0.7.2_amd64.deb
          sudo wget --directory-prefix=/debs/ https://github.com/ShubhamKarala/liboqs-debian/releases/download/0.7.2/liboqs_0.7.2_amd64.deb
          sudo wget --directory-prefix=/debs/ https://github.com/ShubhamKarala/liboqs-debian/releases/download/0.7.2/SHA256SUMS
          cd /debs/ && sha256sum --check --ignore-missing --status SHA256SUMS && dpkg-scanpackages . /dev/null | gzip -9c | sudo tee Packages.gz > /dev/null
          echo "deb [trusted=yes] file:/debs ./" | sudo tee -a /etc/apt/sources.list
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -yV gcc libc6-dev liboqs-dev
      - name: Build liboqs-java
        run: mvn --no-transfer-progress package
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.secret }}